/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.apidemo.dbpapimodell.ConnectionStatus;
import org.example.apidemo.dbpapimodell.TimetableStop;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Connection
 */
class ConnectionTest {
    private final Connection model = new Connection();

    /**
     * Model tests for Connection
     */
    @Test
    void testConnection() {
        // TODO: test Connection
    }

    /**
     * Test the property 'cs'
     */
    @Test
    void csTest() {
        // TODO: test cs
    }

    /**
     * Test the property 'eva'
     */
    @Test
    void evaTest() {
        // TODO: test eva
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ref'
     */
    @Test
    void refTest() {
        // TODO: test ref
    }

    /**
     * Test the property 's'
     */
    @Test
    void sTest() {
        // TODO: test s
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

}
