/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.apidemo.dbpapimodell.DistributorType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DistributorMessage
 */
class DistributorMessageTest {
    private final DistributorMessage model = new DistributorMessage();

    /**
     * Model tests for DistributorMessage
     */
    @Test
    void testDistributorMessage() {
        // TODO: test DistributorMessage
    }

    /**
     * Test the property '_int'
     */
    @Test
    void _intTest() {
        // TODO: test _int
    }

    /**
     * Test the property 'n'
     */
    @Test
    void nTest() {
        // TODO: test n
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

}
