/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoricPlatformChange
 */
class HistoricPlatformChangeTest {
    private final HistoricPlatformChange model = new HistoricPlatformChange();

    /**
     * Model tests for HistoricPlatformChange
     */
    @Test
    void testHistoricPlatformChange() {
        // TODO: test HistoricPlatformChange
    }

    /**
     * Test the property 'ar'
     */
    @Test
    void arTest() {
        // TODO: test ar
    }

    /**
     * Test the property 'cot'
     */
    @Test
    void cotTest() {
        // TODO: test cot
    }

    /**
     * Test the property 'dp'
     */
    @Test
    void dpTest() {
        // TODO: test dp
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

}
