/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.apidemo.dbpapimodell.DistributorMessage;
import org.example.apidemo.dbpapimodell.MessageType;
import org.example.apidemo.dbpapimodell.Priority;
import org.example.apidemo.dbpapimodell.TripLabel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Message
 */
class MessageTest {
    private final Message model = new Message();

    /**
     * Model tests for Message
     */
    @Test
    void testMessage() {
        // TODO: test Message
    }

    /**
     * Test the property 'c'
     */
    @Test
    void cTest() {
        // TODO: test c
    }

    /**
     * Test the property 'cat'
     */
    @Test
    void catTest() {
        // TODO: test cat
    }

    /**
     * Test the property 'del'
     */
    @Test
    void delTest() {
        // TODO: test del
    }

    /**
     * Test the property 'dm'
     */
    @Test
    void dmTest() {
        // TODO: test dm
    }

    /**
     * Test the property 'ec'
     */
    @Test
    void ecTest() {
        // TODO: test ec
    }

    /**
     * Test the property 'elnk'
     */
    @Test
    void elnkTest() {
        // TODO: test elnk
    }

    /**
     * Test the property 'ext'
     */
    @Test
    void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_int'
     */
    @Test
    void _intTest() {
        // TODO: test _int
    }

    /**
     * Test the property 'o'
     */
    @Test
    void oTest() {
        // TODO: test o
    }

    /**
     * Test the property 'pr'
     */
    @Test
    void prTest() {
        // TODO: test pr
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'tl'
     */
    @Test
    void tlTest() {
        // TODO: test tl
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'ts'
     */
    @Test
    void tsTest() {
        // TODO: test ts
    }

}
