/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageType
 */
class MessageTypeTest {
    /**
     * Model tests for MessageType
     */
    @Test
    void testMessageType() {
        // TODO: test MessageType
    }

}
