/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.apidemo.dbpapimodell.ReferenceTripLabel;
import org.example.apidemo.dbpapimodell.ReferenceTripStopLabel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReferenceTrip
 */
class ReferenceTripTest {
    private final ReferenceTrip model = new ReferenceTrip();

    /**
     * Model tests for ReferenceTrip
     */
    @Test
    void testReferenceTrip() {
        // TODO: test ReferenceTrip
    }

    /**
     * Test the property 'c'
     */
    @Test
    void cTest() {
        // TODO: test c
    }

    /**
     * Test the property 'ea'
     */
    @Test
    void eaTest() {
        // TODO: test ea
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'rtl'
     */
    @Test
    void rtlTest() {
        // TODO: test rtl
    }

    /**
     * Test the property 'sd'
     */
    @Test
    void sdTest() {
        // TODO: test sd
    }

}
