/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReferenceTripStopLabel
 */
class ReferenceTripStopLabelTest {
    private final ReferenceTripStopLabel model = new ReferenceTripStopLabel();

    /**
     * Model tests for ReferenceTripStopLabel
     */
    @Test
    void testReferenceTripStopLabel() {
        // TODO: test ReferenceTripStopLabel
    }

    /**
     * Test the property 'eva'
     */
    @Test
    void evaTest() {
        // TODO: test eva
    }

    /**
     * Test the property 'i'
     */
    @Test
    void iTest() {
        // TODO: test i
    }

    /**
     * Test the property 'n'
     */
    @Test
    void nTest() {
        // TODO: test n
    }

    /**
     * Test the property 'pt'
     */
    @Test
    void ptTest() {
        // TODO: test pt
    }

}
