/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.apidemo.dbpapimodell.ReferenceTrip;
import org.example.apidemo.dbpapimodell.ReferenceTripRelationToStop;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReferenceTripRelation
 */
class ReferenceTripRelationTest {
    private final ReferenceTripRelation model = new ReferenceTripRelation();

    /**
     * Model tests for ReferenceTripRelation
     */
    @Test
    void testReferenceTripRelation() {
        // TODO: test ReferenceTripRelation
    }

    /**
     * Test the property 'rt'
     */
    @Test
    void rtTest() {
        // TODO: test rt
    }

    /**
     * Test the property 'rts'
     */
    @Test
    void rtsTest() {
        // TODO: test rts
    }

}
