/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StationData
 */
class StationDataTest {
    private final StationData model = new StationData();

    /**
     * Model tests for StationData
     */
    @Test
    void testStationData() {
        // TODO: test StationData
    }

    /**
     * Test the property 'ds100'
     */
    @Test
    void ds100Test() {
        // TODO: test ds100
    }

    /**
     * Test the property 'eva'
     */
    @Test
    void evaTest() {
        // TODO: test eva
    }

    /**
     * Test the property 'meta'
     */
    @Test
    void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'p'
     */
    @Test
    void pTest() {
        // TODO: test p
    }

}
