/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.apidemo.dbpapimodell.Message;
import org.example.apidemo.dbpapimodell.TimetableStop;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Timetable
 */
class TimetableTest {
    private final Timetable model = new Timetable();

    /**
     * Model tests for Timetable
     */
    @Test
    void testTimetable() {
        // TODO: test Timetable
    }

    /**
     * Test the property 'eva'
     */
    @Test
    void evaTest() {
        // TODO: test eva
    }

    /**
     * Test the property 'm'
     */
    @Test
    void mTest() {
        // TODO: test m
    }

    /**
     * Test the property 's'
     */
    @Test
    void sTest() {
        // TODO: test s
    }

    /**
     * Test the property 'station'
     */
    @Test
    void stationTest() {
        // TODO: test station
    }

}
