/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.apidemo.dbpapimodell;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.apidemo.dbpapimodell.TripLabel;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TripReference
 */
class TripReferenceTest {
    private final TripReference model = new TripReference();

    /**
     * Model tests for TripReference
     */
    @Test
    void testTripReference() {
        // TODO: test TripReference
    }

    /**
     * Test the property 'rt'
     */
    @Test
    void rtTest() {
        // TODO: test rt
    }

    /**
     * Test the property 'tl'
     */
    @Test
    void tlTest() {
        // TODO: test tl
    }

}
