/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Address
 */
class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'houseNumber'
     */
    @Test
    void houseNumberTest() {
        // TODO: test houseNumber
    }

    /**
     * Test the property 'street'
     */
    @Test
    void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'zipcode'
     */
    @Test
    void zipcodeTest() {
        // TODO: test zipcode
    }

}
