/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.staDa.model.OpeningHours;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DoubleScheduleAvailability
 */
class DoubleScheduleAvailabilityTest {
    private final DoubleScheduleAvailability model = new DoubleScheduleAvailability();

    /**
     * Model tests for DoubleScheduleAvailability
     */
    @Test
    void testDoubleScheduleAvailability() {
        // TODO: test DoubleScheduleAvailability
    }

    /**
     * Test the property 'friday1'
     */
    @Test
    void friday1Test() {
        // TODO: test friday1
    }

    /**
     * Test the property 'friday2'
     */
    @Test
    void friday2Test() {
        // TODO: test friday2
    }

    /**
     * Test the property 'monday1'
     */
    @Test
    void monday1Test() {
        // TODO: test monday1
    }

    /**
     * Test the property 'monday2'
     */
    @Test
    void monday2Test() {
        // TODO: test monday2
    }

    /**
     * Test the property 'saturday1'
     */
    @Test
    void saturday1Test() {
        // TODO: test saturday1
    }

    /**
     * Test the property 'saturday2'
     */
    @Test
    void saturday2Test() {
        // TODO: test saturday2
    }

    /**
     * Test the property 'sunday1'
     */
    @Test
    void sunday1Test() {
        // TODO: test sunday1
    }

    /**
     * Test the property 'sunday2'
     */
    @Test
    void sunday2Test() {
        // TODO: test sunday2
    }

    /**
     * Test the property 'thursday1'
     */
    @Test
    void thursday1Test() {
        // TODO: test thursday1
    }

    /**
     * Test the property 'thursday2'
     */
    @Test
    void thursday2Test() {
        // TODO: test thursday2
    }

    /**
     * Test the property 'tuesday1'
     */
    @Test
    void tuesday1Test() {
        // TODO: test tuesday1
    }

    /**
     * Test the property 'tuesday2'
     */
    @Test
    void tuesday2Test() {
        // TODO: test tuesday2
    }

    /**
     * Test the property 'wednesday1'
     */
    @Test
    void wednesday1Test() {
        // TODO: test wednesday1
    }

    /**
     * Test the property 'wednesday2'
     */
    @Test
    void wednesday2Test() {
        // TODO: test wednesday2
    }

}
