/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.staDa.model.DoubleSchedule;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MobilityServiceStaff
 */
class MobilityServiceStaffTest {
    private final MobilityServiceStaff model = new MobilityServiceStaff();

    /**
     * Model tests for MobilityServiceStaff
     */
    @Test
    void testMobilityServiceStaff() {
        // TODO: test MobilityServiceStaff
    }

    /**
     * Test the property 'availability'
     */
    @Test
    void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'staffOnSite'
     */
    @Test
    void staffOnSiteTest() {
        // TODO: test staffOnSite
    }

}
