/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.staDa.model.GeographicPoint;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiL100Identifier
 */
class RiL100IdentifierTest {
    private final RiL100Identifier model = new RiL100Identifier();

    /**
     * Model tests for RiL100Identifier
     */
    @Test
    void testRiL100Identifier() {
        // TODO: test RiL100Identifier
    }

    /**
     * Test the property 'geographicCoordinates'
     */
    @Test
    void geographicCoordinatesTest() {
        // TODO: test geographicCoordinates
    }

    /**
     * Test the property 'hasSteamPermission'
     */
    @Test
    void hasSteamPermissionTest() {
        // TODO: test hasSteamPermission
    }

    /**
     * Test the property 'isMain'
     */
    @Test
    void isMainTest() {
        // TODO: test isMain
    }

    /**
     * Test the property 'primaryLocationCode'
     */
    @Test
    void primaryLocationCodeTest() {
        // TODO: test primaryLocationCode
    }

    /**
     * Test the property 'rilIdentifier'
     */
    @Test
    void rilIdentifierTest() {
        // TODO: test rilIdentifier
    }

    /**
     * Test the property 'steamPermission'
     */
    @Test
    void steamPermissionTest() {
        // TODO: test steamPermission
    }

}
