/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.staDa.model.OpeningHours;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScheduleAvailability
 */
class ScheduleAvailabilityTest {
    private final ScheduleAvailability model = new ScheduleAvailability();

    /**
     * Model tests for ScheduleAvailability
     */
    @Test
    void testScheduleAvailability() {
        // TODO: test ScheduleAvailability
    }

    /**
     * Test the property 'friday'
     */
    @Test
    void fridayTest() {
        // TODO: test friday
    }

    /**
     * Test the property 'holiday'
     */
    @Test
    void holidayTest() {
        // TODO: test holiday
    }

    /**
     * Test the property 'monday'
     */
    @Test
    void mondayTest() {
        // TODO: test monday
    }

    /**
     * Test the property 'saturday'
     */
    @Test
    void saturdayTest() {
        // TODO: test saturday
    }

    /**
     * Test the property 'sunday'
     */
    @Test
    void sundayTest() {
        // TODO: test sunday
    }

    /**
     * Test the property 'thursday'
     */
    @Test
    void thursdayTest() {
        // TODO: test thursday
    }

    /**
     * Test the property 'tuesday'
     */
    @Test
    void tuesdayTest() {
        // TODO: test tuesday
    }

    /**
     * Test the property 'wednesday'
     */
    @Test
    void wednesdayTest() {
        // TODO: test wednesday
    }

}
