/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.staDa.model.Address;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SZentrale
 */
class SZentraleTest {
    private final SZentrale model = new SZentrale();

    /**
     * Model tests for SZentrale
     */
    @Test
    void testSZentrale() {
        // TODO: test SZentrale
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'internalFaxNumber'
     */
    @Test
    void internalFaxNumberTest() {
        // TODO: test internalFaxNumber
    }

    /**
     * Test the property 'internalPhoneNumber'
     */
    @Test
    void internalPhoneNumberTest() {
        // TODO: test internalPhoneNumber
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'number'
     */
    @Test
    void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'publicFaxNumber'
     */
    @Test
    void publicFaxNumberTest() {
        // TODO: test publicFaxNumber
    }

    /**
     * Test the property 'publicPhoneNumber'
     */
    @Test
    void publicPhoneNumberTest() {
        // TODO: test publicPhoneNumber
    }

}
