/*
 * StaDa - Station Data
 * An API providing master data for german railway stations managed by DB InfraGo AG.  ## License The usage of the data is subject to the Creative Commons Attribution 4.0 International (CC BY 4.0) license.\"
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: StaDa.API@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.staDa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WirelessLan
 */
class WirelessLanTest {
    private final WirelessLan model = new WirelessLan();

    /**
     * Model tests for WirelessLan
     */
    @Test
    void testWirelessLan() {
        // TODO: test WirelessLan
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'installDate'
     */
    @Test
    void installDateTest() {
        // TODO: test installDate
    }

    /**
     * Test the property 'product'
     */
    @Test
    void productTest() {
        // TODO: test product
    }

}
