/*
 * FaSta - Station Facilities Status
 * * A RESTful webservice to retrieve data about the operational state of public elevators and escalators in german railway stations operated by DB InfraGO AG.
 *
 * The version of the OpenAPI document: 2.1.388
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.faSta.api;

import org.example.faSta.model.Facility;
import java.util.Set;
import org.example.faSta.model.Station;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for FaStaApi
 */
@Disabled
public class FaStaApiTest {

    private final FaStaApi api = new FaStaApi();

    
    /**
     * 
     *
     * Access to public facilities (escalators and elevators) in railway stations
     */
    @Test
    public void findFacilitiesTest()  {
        Set<String> type = null;
        Set<String> state = null;
        Set<Long> equipmentnumbers = null;
        Long stationnumber = null;
        List<String> area = null;
        List<Facility> response = api.findFacilities(type, state, equipmentnumbers, stationnumber, area);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns information about a station (and its corresponding facilities) identified by a stationnumber.
     */
    @Test
    public void findStationByStationNumberTest()  {
        Long stationnumber = null;
        Station response = api.findStationByStationNumber(stationnumber);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the facility identified by its equipmentnumber.
     */
    @Test
    public void getFacilityByEquipmentNumberTest()  {
        Long equipmentnumber = null;
        Facility response = api.getFacilityByEquipmentNumber(equipmentnumber);

        // TODO: test validations
    }
    
}