/*
 * db-rest
 * A clean REST API wrapping around the Deutsche Bahn API.
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.dbRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.dbRest.model.Departure;
import org.example.dbRest.model.DepartureWrapperMetadata;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ArrivalWrapper
 */
class ArrivalWrapperTest {
    private final ArrivalWrapper model = new ArrivalWrapper();

    /**
     * Model tests for ArrivalWrapper
     */
    @Test
    void testArrivalWrapper() {
        // TODO: test ArrivalWrapper
    }

    /**
     * Test the property 'departures'
     */
    @Test
    void departuresTest() {
        // TODO: test departures
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
