/*
 * db-rest
 * A clean REST API wrapping around the Deutsche Bahn API.
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.dbRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DepartureWrapperMetadata
 */
class DepartureWrapperMetadataTest {
    private final DepartureWrapperMetadata model = new DepartureWrapperMetadata();

    /**
     * Model tests for DepartureWrapperMetadata
     */
    @Test
    void testDepartureWrapperMetadata() {
        // TODO: test DepartureWrapperMetadata
    }

    /**
     * Test the property 'generatedAt'
     */
    @Test
    void generatedAtTest() {
        // TODO: test generatedAt
    }

    /**
     * Test the property 'stationName'
     */
    @Test
    void stationNameTest() {
        // TODO: test stationName
    }

}
