/*
 * db-rest
 * A clean REST API wrapping around the Deutsche Bahn API.
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.dbRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.dbRest.model.Operator;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Line
 */
class LineTest {
    private final Line model = new Line();

    /**
     * Model tests for Line
     */
    @Test
    void testLine() {
        // TODO: test Line
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fahrtNr'
     */
    @Test
    void fahrtNrTest() {
        // TODO: test fahrtNr
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isPublic'
     */
    @Test
    void isPublicTest() {
        // TODO: test isPublic
    }

    /**
     * Test the property 'adminCode'
     */
    @Test
    void adminCodeTest() {
        // TODO: test adminCode
    }

    /**
     * Test the property 'productName'
     */
    @Test
    void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'mode'
     */
    @Test
    void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'product'
     */
    @Test
    void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'operator'
     */
    @Test
    void operatorTest() {
        // TODO: test operator
    }

}
