/*
 * db-rest
 * A clean REST API wrapping around the Deutsche Bahn API.
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.dbRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Products
 */
class ProductsTest {
    private final Products model = new Products();

    /**
     * Model tests for Products
     */
    @Test
    void testProducts() {
        // TODO: test Products
    }

    /**
     * Test the property 'nationalExpress'
     */
    @Test
    void nationalExpressTest() {
        // TODO: test nationalExpress
    }

    /**
     * Test the property 'national'
     */
    @Test
    void nationalTest() {
        // TODO: test national
    }

    /**
     * Test the property 'regionalExpress'
     */
    @Test
    void regionalExpressTest() {
        // TODO: test regionalExpress
    }

    /**
     * Test the property 'regional'
     */
    @Test
    void regionalTest() {
        // TODO: test regional
    }

    /**
     * Test the property 'suburban'
     */
    @Test
    void suburbanTest() {
        // TODO: test suburban
    }

    /**
     * Test the property 'bus'
     */
    @Test
    void busTest() {
        // TODO: test bus
    }

    /**
     * Test the property 'ferry'
     */
    @Test
    void ferryTest() {
        // TODO: test ferry
    }

    /**
     * Test the property 'subway'
     */
    @Test
    void subwayTest() {
        // TODO: test subway
    }

    /**
     * Test the property 'tram'
     */
    @Test
    void tramTest() {
        // TODO: test tram
    }

    /**
     * Test the property 'taxi'
     */
    @Test
    void taxiTest() {
        // TODO: test taxi
    }

}
