/*
 * db-rest
 * A clean REST API wrapping around the Deutsche Bahn API.
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.dbRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.dbRest.model.Departure;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StopsIdDeparturesGet2XXResponse
 */
class StopsIdDeparturesGet2XXResponseTest {
    private final StopsIdDeparturesGet2XXResponse model = new StopsIdDeparturesGet2XXResponse();

    /**
     * Model tests for StopsIdDeparturesGet2XXResponse
     */
    @Test
    void testStopsIdDeparturesGet2XXResponse() {
        // TODO: test StopsIdDeparturesGet2XXResponse
    }

    /**
     * Test the property 'departureList'
     */
    @Test
    void departureListTest() {
        // TODO: test departureList
    }

}
