/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.timetables.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.timetables.model.EventStatus;
import org.example.timetables.model.Message;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Event
 */
class EventTest {
    private final Event model = new Event();

    /**
     * Model tests for Event
     */
    @Test
    void testEvent() {
        // TODO: test Event
    }

    /**
     * Test the property 'cde'
     */
    @Test
    void cdeTest() {
        // TODO: test cde
    }

    /**
     * Test the property 'clt'
     */
    @Test
    void cltTest() {
        // TODO: test clt
    }

    /**
     * Test the property 'cp'
     */
    @Test
    void cpTest() {
        // TODO: test cp
    }

    /**
     * Test the property 'cpth'
     */
    @Test
    void cpthTest() {
        // TODO: test cpth
    }

    /**
     * Test the property 'cs'
     */
    @Test
    void csTest() {
        // TODO: test cs
    }

    /**
     * Test the property 'ct'
     */
    @Test
    void ctTest() {
        // TODO: test ct
    }

    /**
     * Test the property 'dc'
     */
    @Test
    void dcTest() {
        // TODO: test dc
    }

    /**
     * Test the property 'hi'
     */
    @Test
    void hiTest() {
        // TODO: test hi
    }

    /**
     * Test the property 'l'
     */
    @Test
    void lTest() {
        // TODO: test l
    }

    /**
     * Test the property 'm'
     */
    @Test
    void mTest() {
        // TODO: test m
    }

    /**
     * Test the property 'pde'
     */
    @Test
    void pdeTest() {
        // TODO: test pde
    }

    /**
     * Test the property 'pp'
     */
    @Test
    void ppTest() {
        // TODO: test pp
    }

    /**
     * Test the property 'ppth'
     */
    @Test
    void ppthTest() {
        // TODO: test ppth
    }

    /**
     * Test the property 'ps'
     */
    @Test
    void psTest() {
        // TODO: test ps
    }

    /**
     * Test the property 'pt'
     */
    @Test
    void ptTest() {
        // TODO: test pt
    }

    /**
     * Test the property 'tra'
     */
    @Test
    void traTest() {
        // TODO: test tra
    }

    /**
     * Test the property 'wings'
     */
    @Test
    void wingsTest() {
        // TODO: test wings
    }

}
