/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.timetables.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.timetables.model.Connection;
import org.example.timetables.model.Event;
import org.example.timetables.model.HistoricDelay;
import org.example.timetables.model.HistoricPlatformChange;
import org.example.timetables.model.Message;
import org.example.timetables.model.ReferenceTripRelation;
import org.example.timetables.model.TripLabel;
import org.example.timetables.model.TripReference;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimetableStop
 */
class TimetableStopTest {
    private final TimetableStop model = new TimetableStop();

    /**
     * Model tests for TimetableStop
     */
    @Test
    void testTimetableStop() {
        // TODO: test TimetableStop
    }

    /**
     * Test the property 'ar'
     */
    @Test
    void arTest() {
        // TODO: test ar
    }

    /**
     * Test the property 'conn'
     */
    @Test
    void connTest() {
        // TODO: test conn
    }

    /**
     * Test the property 'dp'
     */
    @Test
    void dpTest() {
        // TODO: test dp
    }

    /**
     * Test the property 'eva'
     */
    @Test
    void evaTest() {
        // TODO: test eva
    }

    /**
     * Test the property 'hd'
     */
    @Test
    void hdTest() {
        // TODO: test hd
    }

    /**
     * Test the property 'hpc'
     */
    @Test
    void hpcTest() {
        // TODO: test hpc
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'm'
     */
    @Test
    void mTest() {
        // TODO: test m
    }

    /**
     * Test the property 'ref'
     */
    @Test
    void refTest() {
        // TODO: test ref
    }

    /**
     * Test the property 'rtr'
     */
    @Test
    void rtrTest() {
        // TODO: test rtr
    }

    /**
     * Test the property 'tl'
     */
    @Test
    void tlTest() {
        // TODO: test tl
    }

}
