/*
 * Timetables
 * API for passenger information for train stations operated by DB Station&Service AG
 *
 * The version of the OpenAPI document: 1.0.213
 * Contact: dbopendata@deutschebahn.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.timetables.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.example.timetables.model.TripType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TripLabel
 */
class TripLabelTest {
    private final TripLabel model = new TripLabel();

    /**
     * Model tests for TripLabel
     */
    @Test
    void testTripLabel() {
        // TODO: test TripLabel
    }

    /**
     * Test the property 'c'
     */
    @Test
    void cTest() {
        // TODO: test c
    }

    /**
     * Test the property 'f'
     */
    @Test
    void fTest() {
        // TODO: test f
    }

    /**
     * Test the property 'n'
     */
    @Test
    void nTest() {
        // TODO: test n
    }

    /**
     * Test the property 'o'
     */
    @Test
    void oTest() {
        // TODO: test o
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

}
