/*
 * FaSta - Station Facilities Status
 * * A RESTful webservice to retrieve data about the operational state of public elevators and escalators in german railway stations operated by DB InfraGO AG.
 *
 * The version of the OpenAPI document: 2.1.388
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.faSta.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Facility
 */
class FacilityTest {
    private final Facility model = new Facility();

    /**
     * Model tests for Facility
     */
    @Test
    void testFacility() {
        // TODO: test Facility
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'equipmentnumber'
     */
    @Test
    void equipmentnumberTest() {
        // TODO: test equipmentnumber
    }

    /**
     * Test the property 'geocoordX'
     */
    @Test
    void geocoordXTest() {
        // TODO: test geocoordX
    }

    /**
     * Test the property 'geocoordY'
     */
    @Test
    void geocoordYTest() {
        // TODO: test geocoordY
    }

    /**
     * Test the property 'operatorname'
     */
    @Test
    void operatornameTest() {
        // TODO: test operatorname
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateExplanation'
     */
    @Test
    void stateExplanationTest() {
        // TODO: test stateExplanation
    }

    /**
     * Test the property 'stationnumber'
     */
    @Test
    void stationnumberTest() {
        // TODO: test stationnumber
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

}
