/*
 * FaSta - Station Facilities Status
 * * A RESTful webservice to retrieve data about the operational state of public elevators and escalators in german railway stations operated by DB InfraGO AG.
 *
 * The version of the OpenAPI document: 2.1.388
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.faSta.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.example.faSta.model.Facility;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Station
 */
class StationTest {
    private final Station model = new Station();

    /**
     * Model tests for Station
     */
    @Test
    void testStation() {
        // TODO: test Station
    }

    /**
     * Test the property 'facilities'
     */
    @Test
    void facilitiesTest() {
        // TODO: test facilities
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'stationnumber'
     */
    @Test
    void stationnumberTest() {
        // TODO: test stationnumber
    }

}
